<a href="https://colab.research.google.com/github/newjay608/ABTests/blob/main/00_introduction_to_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Introduction to PyTorch

In [3]:
import sys
import platform
import torch
import numpy as np
import pandas as pd
import sklearn as sk

In [4]:
has_gpu = torch.cuda.is_available()
has_mps = torch.backends.mps.is_built()

device = "mps" if torch.backends.mps.is_available() \
  else "gpu" if torch.cuda.is_available() else "cpu"

print(f"Python Platform: {platform.platform()}")
print(f"PyTorch Version: {torch.__version__}")
print()
print(f"Python Version {sys.version_info}")
print(f"Pandas Version {pd.__version__}")
print(f"Scikit Version {sk.__version__}")
print(f"GPU is available "if has_gpu else "GPU NOT AVIALABLE")
print(f"MPS (Apple Metal) is available "if has_gpu else "APLLE METAL NOT AVIALABLE")
print(f"Target Device {device}")

Python Platform: Linux-6.1.58+-x86_64-with-glibc2.35
PyTorch Version: 2.1.0+cu121

Python Version sys.version_info(major=3, minor=10, micro=12, releaselevel='final', serial=0)
Pandas Version 1.5.3
Scikit Version 1.2.2
GPU is available 
MPS (Apple Metal) is available 
Target Device gpu


## Creating Tensors

Tensors are immutable, algebraic object that decribes a multilinear realitionship between sets of algebraic objrects in a vector space

Its a multi-dimensional array of numbers, but they are not just numbers, but they also have geometry and the object is invariant undera change of coordiantes and has compoenents that change in special, predictable way under a change of cooridnates. Change of cooridnates here means you can apply any cooridnate system the lentgh (maginidute) is invariate. The components change with each coordiante system in which the vector is placed

A simplistic example of tensor is a scalar, scalars as just a number

In [5]:
scalar = torch.tensor(7)
print(f"scalar {scalar}")
print(f"scalar item value {scalar.item()}")
print(f"scalar ndim {scalar.ndim}")
print(f"scalar shape {scalar.shape}")


scalar 7
scalar item value 7
scalar ndim 0
scalar shape torch.Size([])


In [6]:
vector = torch.tensor([7,7])
print(f"vector {vector}")
print(f"vector ndim {vector.ndim}")
print(f"vector shape {vector.shape}")

vector tensor([7, 7])
vector ndim 1
vector shape torch.Size([2])


In [7]:
MATRIX = torch.tensor([[7,8],
                       [9,10],
                       [11,3]])
print(f"vector {MATRIX}")
print(f"vector ndim {MATRIX.ndim}")
print(f"vector shape {MATRIX.shape}")
print(f"first element {MATRIX[0]}")
print(f"second element {MATRIX[1]}")

vector tensor([[ 7,  8],
        [ 9, 10],
        [11,  3]])
vector ndim 2
vector shape torch.Size([3, 2])
first element tensor([7, 8])
second element tensor([ 9, 10])


In [8]:
TENSOR = torch.tensor([[[1,2,3],
                      [4,5,6],
                      [7,8,9]]])
print(f"vector {TENSOR}")
print(f"vector ndim {TENSOR.ndim}")
print(f"vector shape {TENSOR.shape}")

vector tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])
vector ndim 3
vector shape torch.Size([1, 3, 3])


Tensors can represent almost anything. The dimensions go outer to inner.
  
The above tensor can represent a sales number for three products in three stores
or.
first row can be days of the week and second and third rows can be stake and almond sales
  
**That means there's 1 dimension of 3 by 3.**

Name: Scalar
What is it?: a single number
num of dimensions 0
Lower or upper : Lower(a)
  

Name: Vector
What is it?: a a number with directions
num of dimensions 0
Lower or upper: Lower (y)


Name: Matrix
What is it?: a 2-demensional array of numbers
num of dimensions 2
Lower or upper: Upper (Q)


Name: Tensor
What is it? an n-dimensional array of numbers
number of dimensions: can be any number - a 0 dimension is a scalar; vector is a 1-dimensional tensor
Lower or upper: Upper(X)




### Random tensors

Why Random Tensors are important?
Random tensors (numbers) is what DNNs learn and as they learn the models adjust these random tensors to better represent the data

In [9]:
random_tensor = torch.rand(3,4)
print(random_tensor)
print(f"size {random_tensor.size()}")
print(f"ndim {random_tensor.ndim}")

tensor([[0.8034, 0.9380, 0.1792, 0.4209],
        [0.1858, 0.2581, 0.4899, 0.0487],
        [0.3473, 0.4160, 0.6171, 0.7735]])
size torch.Size([3, 4])
ndim 2


In [10]:
random_tensor = torch.rand(2, 5, 4)
print(random_tensor)
print(f"size {random_tensor.shape}")
print(f"ndim {random_tensor.ndim}")

tensor([[[0.3154, 0.3338, 0.8002, 0.2182],
         [0.6569, 0.2051, 0.6118, 0.3696],
         [0.6158, 0.7826, 0.5364, 0.4362],
         [0.6281, 0.1874, 0.1008, 0.1669],
         [0.1636, 0.3230, 0.1923, 0.6862]],

        [[0.3936, 0.7628, 0.4962, 0.7645],
         [0.8831, 0.2241, 0.2219, 0.7120],
         [0.6916, 0.8895, 0.2096, 0.0951],
         [0.5491, 0.7222, 0.7052, 0.8153],
         [0.2078, 0.6003, 0.6447, 0.6942]]])
size torch.Size([2, 5, 4])
ndim 3


In [11]:
# create a random tesnor with similar shape to an image tensor, pytorch does the
# work behind the scene to generate a tensor from an image
random_image_size_tensor = torch.rand(size=(224,224,3))
print(f"size {random_image_size_tensor.shape}")
print(f"ndim {random_image_size_tensor.ndim}")

size torch.Size([224, 224, 3])
ndim 3


### Zeros and Ones

In [12]:
# Create a tensor of all zeros
zeros = torch.zeros(size =(1,3,3))
print(zeros)
print(f"size {zeros.shape}")
print(f"ndim {zeros.ndim}")

tensor([[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]])
size torch.Size([1, 3, 3])
ndim 3


In [13]:
ones = torch.ones(size =(2,3,3))
print(ones)
print(f"size {ones.shape}")
print(f"ndim {ones.ndim}")

tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]])
size torch.Size([2, 3, 3])
ndim 3


### Create a range of tensors and tensors-like

In [14]:
# torch arange  - range function is depricated

#depricated
#one_to_ten = torch.range(1,11)
#print(one_to_ten)

one_to_ten = torch.arange(1,11)
print(one_to_ten)

# step
one_to_thousand = torch.arange(1,1000, step=80)
print(one_to_thousand)

# creating tensors like
ten_zeros = torch.zeros_like(one_to_ten)
print(ten_zeros)

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])
tensor([  1,  81, 161, 241, 321, 401, 481, 561, 641, 721, 801, 881, 961])
tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])


### Tensor datatypes

**Note** : Tensor data is one of the big 3 errors in pytorch and deep learning
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [15]:
#Float 32 tensor - default float data type
float32_tensor = torch.tensor([3.0,6.0,9.0],
                              dtype=None, # what datatypes https://pytorch.org/docs/stable/tensors.html
                              device=None, # What device is the tensor is on
                              requires_grad=False) # to track gradients with this tensor or not
print(float32_tensor)

#Float 32 tensor
float32_tensor2 = torch.tensor([3.0,6.0,9.0],
                              dtype=None, # what datatypes https://pytorch.org/docs/stable/tensors.html
                              device="cuda",
                              requires_grad=False)
print(float32_tensor2)

# converting tensor data types
float16_tensor = float32_tensor.type(torch.float16)
print(float16_tensor)

tensor([3., 6., 9.])
tensor([3., 6., 9.], device='cuda:0')
tensor([3., 6., 9.], dtype=torch.float16)


In [16]:
float32_tensor * float16_tensor

tensor([ 9., 36., 81.])

In [17]:
# Expected all tensors to be on the same device error is thrown
# float32_tensor * float32_tensor2

#changing the device for a tensor
int32_tensor = torch.tensor([3,4,5], dtype=torch.int32)
print(f" int32_tensor converted to {int32_tensor.dtype}")
print(f" int32_tensor is on device {int32_tensor.device}")

cuda0 = torch.device('cuda:0')
int32_tensor = int32_tensor.to(cuda0, dtype=torch.float32)
print(f" int32_tensor converted to {int32_tensor.dtype}")
print(f" int32_tensor is moved device to {int32_tensor.device}")

# implicit type conversion
int32_tensor = torch.tensor([3,5,6], dtype=torch.int32)
float32_tensor * int32_tensor

 int32_tensor converted to torch.int32
 int32_tensor is on device cpu
 int32_tensor converted to torch.float32
 int32_tensor is moved device to cuda:0


tensor([ 9., 30., 54.])

### Getting information from tensor attributes

dtype - tensor.dtype, device -tensor.device and shape - tensor.shape

In [18]:
print(f"type {int32_tensor.dtype}")
print(f"shape {int32_tensor.shape}")
print(f"device {int32_tensor.device}")

print(f"type {float32_tensor2.dtype}")
print(f"shape {float32_tensor2.shape}")
print(f"device {float32_tensor2.device}")

type torch.int32
shape torch.Size([3])
device cpu
type torch.float32
shape torch.Size([3])
device cuda:0


### Manipulating Tensors
** Addition.   
** Substraction.   
** Multiplication (element-wise).   
** Division.   
** Matrix Multiplication.   


### Matrix Manipulation
There are two ways.   
** Element-wise multiplication.       
** Matrix multiplication.  (dot product)  

In [19]:
tensor = torch.tensor([2,5,8,9])
# addition
print(tensor + 10)
print(torch.add(tensor,10))

# multiplication
print(tensor * 10)
print(torch.mul(tensor,10))
# substraction
print(tensor - 10)
print(torch.sub(tensor,10))
# division
print(tensor / 10)
print(torch.div(tensor,10))


tensor([12, 15, 18, 19])
tensor([12, 15, 18, 19])
tensor([20, 50, 80, 90])
tensor([20, 50, 80, 90])
tensor([-8, -5, -2, -1])
tensor([-8, -5, -2, -1])
tensor([0.2000, 0.5000, 0.8000, 0.9000])
tensor([0.2000, 0.5000, 0.8000, 0.9000])


One of the most common operations in machine learning and deep learning algorithms (like neural networks) is matrix multiplication.  
  
PyTorch implements matrix multiplication functionality in the torch.matmul() method.  
  
The main two rules for matrix multiplication to remember are:  
  
The inner dimensions must match:  
(3, 2) @ (3, 2) won't work.  
(2, 3) @ (3, 2) will work.  
(3, 2) @ (2, 3) will work.
The resulting matrix has the shape of the outer dimensions:  
(2, 3) @ (3, 2) -> (2, 2).
(3, 2) @ (2, 3) -> (3, 3).
Note: "@" in Python is the symbol for matrix multiplication.  

Resource: You can see all of the rules for matrix multiplication using torch.matmul() in the PyTorch documentation.  
  
Let's create a tensor and perform element-wise multiplication and matrix multiplication on it.    

In [20]:
tensor1 = torch.tensor([[2,3,4],
                        [3,6,9]], dtype=torch.float32)

tensor2 = torch. tensor([[2,3],
                         [3,6],
                         [4, 9]], dtype=torch.float32)

# @  operator or matul function can be used
tensor3 = torch.matmul(tensor1, tensor2)
tensor3 = tensor1 @ tensor2
print(tensor3)



tensor([[ 29.,  60.],
        [ 60., 126.]])


In [22]:
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])

tensor_B = torch.tensor([[7, 10],
                         [8,11],
                         [9, 12]])

#torch.mm(tensor_A, tensor_B) #torch.mm is same as torch.matmul (its an aleas for the matmul function)

# torch.matmul(tensor_A, tensor_B). # throws a shape error

print(tensor_B.T)

tensor_C = torch.matmul(tensor_A, tensor_B.T)

print(tensor_C)



tensor([[ 7,  8,  9],
        [10, 11, 12]])
tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])


# Finding the min, max, mean, sum etc (tensor aggregations)


In [27]:
x = torch.arange(0,100,10)
print(x)
print(x.dtype)

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])
torch.int64


In [34]:
# Find the min
print(torch.min(x))
print(x.min())

# Find the max
print(torch.max(x))
print(x.max())

# Find the mean
print(torch.mean(x.type(torch.float32)))  # torch.mean() function requires the float32 datatype
print(x.type(torch.float32).mean())

# Find the sum
print(torch.sum(x))
print(x.sum())

# Find positional min and max - index of min and max values
print(torch.argmin(x))
print(x.argmin())

print(torch.argmax(x))
print(x.argmax())

tensor(0)
tensor(0)
tensor(90)
tensor(90)
tensor(45.)
tensor(45.)
tensor(450)
tensor(450)
tensor(0)
tensor(0)
tensor(9)
tensor(9)
